# -*- coding: utf-8 -*-
"""MoodWise – Your Emotion Companion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pODNu1LDYjBckgzlZVURTTn_MfmltqlZ
"""

# 🧠 Emotion-Aware Activity Recommender

# Function to recommend activity based on emotion
def recommend_activity(user_input):
    user_input = user_input.lower()

    # Emotion keywords mapped to activities and reasons
    emotion_map = {
        "angry": ("Go for a brisk walk 🚶", "Physical activity helps reduce stress hormones like cortisol."),
        "frustrated": ("Do deep breathing 🧘‍♀️", "Breathing resets your nervous system."),
        "sad": ("Listen to calm music 🎵", "Music activates dopamine and soothes emotional centers."),
        "lonely": ("Call or text a friend 📱", "Social connection instantly uplifts mood."),
        "anxious": ("Try journaling ✍️", "Writing your thoughts reduces mental clutter."),
        "tired": ("Take a power nap or drink water 💧", "You may be low on rest or hydration."),
        "bored": ("Try a creative hobby 🎨", "Hobbies re-engage your brain and kill boredom."),
        "overwhelmed": ("Take a break & declutter your space 🧹", "Your mind mirrors your environment."),
        "jealous": ("Write what you’re grateful for 💖", "Gratitude shifts focus from others to self."),
        "guilty": ("Practice self-forgiveness 🙏", "You grow by accepting, not punishing yourself."),
        "insecure": ("Repeat a self-affirmation 💬", "Your words can reprogram your thoughts."),
        "happy": ("Share your joy with someone! 😊", "Spreading happiness increases it."),
        "excited": ("Channel it into action! 🏃", "Use this energy to start something productive."),
        "confused": ("Talk to a mentor or write it out 📄", "Externalizing clears mental fog."),
        "nervous": ("Stretch or pace slowly 🤸", "Moves adrenaline and calms your body.")
    }

    # Find emotion from input
    for emotion in emotion_map:
        if emotion in user_input:
            activity, reason = emotion_map[emotion]
            return f"😌 Detected Emotion: **{emotion.capitalize()}**\n👉 Recommended: **{activity}**\n💡 Why: {reason}"

    return "🤔 Sorry, I couldn't detect the emotion. Try using common words like 'sad', 'angry', 'anxious', etc."

# 📌 Input box
print("Welcome to Emotion Activity Recommender!")
user_feeling = input("💬 How are you feeling right now? ")

# 📈 Recommendation
response = recommend_activity(user_feeling)
print("\n" + response)